const questions = [
    // BLUE QUESTIONS
    {
        code: "QNX@2023@BLUE",
        title: "Team Blue Question #1 - Exploring Letter Substitution and Binary Conversion",
        description: `Use "Letter Substitution" to compute the word QUESTRONIX Then Let's take this decimal for a ride on the binary express!`,
        answer: "10100010",
        reward: "151 SE",
    },
    {
        code: "SCF@2023@BLUE",
        title: "Team Blue Question #2 - Find the word",
        description: "What elusive goal did Questronix triumphantly snatch in 1987? It's hidden within the depths of the Questronix website, waiting to be discovered by the curious and determined.",
        answer: "THE INCEPTION",
        reward: "50 NE",
    },
    {
        code: "TEAM BLUE",
        title: "Team Blue Question #3 - Caesar Cipher",
        description: `"GEQEVEHIVMI" - Shift is in 1 - 5. That's absolute :)`,
        answer: "CAMARADERIE",
        reward: "311 NW",
    },
    {
        code: "ORANGE",
        title: "Team Blue Question #4 - phlbrie kcco",
        description: `"SRGLHVE HEOAIEN ADACEMT" - Re-arrange the title to identify the cipher. It's not none, inline or flex`,
        answer: "SHARED GOAL ACHIEVEMENT",
        reward: "63 NE",
    },
    {
        code: "FINAL CODE",
        title: "Team Blue Question #5 - Morse Code :)",
        description: `".. - ... / -. --- - / - .... . / .- -. ... .-- . .-." - Unlocking the treasure trove isn't exactly rocket science - all it takes is a few taps of your fingers and the Final Code. It sounds simple, but beware - this digital labyrinth may have more surprises in store than you think.`,
        answer: "FINAL CODE",
        reward: "CONGRATULATIONS <3",
    },
    //ORANGE QUESTIONS
    {
        code: "QNX@2023@ORANGE",
        title: `Team Orange Question #1 - Letter Substitution and Binary Conversion`,
        description: `Use "Letter Substitution" to compute the word QUESTRONIX, Then Let's give this number a binary makeover and watch it go from decimal to dazzling!`,
        answer: "10100010",
        reward: "211 SW",
    },
    {
        code: "SCF@2023@ORANGE",
        title: "Team Orange Question #2 - Caesar Cipher",
        description: "What grand achievement did Questronix unlock in 2000? It's a mystery that lies within the depths of the Questronix website - a treasure worth seeking, but not one that gives itself up easily.",
        answer: "SYSTEM INTEGRATOR",
        reward: "137 SE",
    },
    {
        code: "TEAM ORANGE",
        title: "Team Orange Question #3 - Find the word",
        description: `"PKCAPDANJAO" Shift is in 1 - 5. Well that's negative`,
        answer: "TOGETHERNESS",
        reward: "7 N",
    },
    {
        code: "BLUE",
        title: "Team Orange Question #4 - phlbrie kcco",
        description: `"GUOIAITS RPNNCVI OBDGTIE" - Re-arrange the title to identify the cipher. It's not none, inline or flex`,
        answer: "GROUP BONDING ACTIVITIES",
        reward: "90 E",
    },
    {
        code: "LAST CODE",
        title: "Team Orange Question #5 - Morse Code :)",
        description: `"- .... .. ... / .. ... / -. --- - / - .... . / .- -. ... .-- . .-." - Well, it's not rocket science - just a few taps of your fingers and the Last Code will unlock the treasure trove. A cinch, really. But don't let that fool you, there's more than meets the eye to this digital labyrinth. `,
        answer: "LAST CODE",
        reward: "CONGRATULATIONS <3",
    },
    //Test Code
    {
        code: "TEST CODE",
        title: "Default #1 - Introduction :)",
        description: `Welcome to the Scavenger Hunt game! This exciting adventure will take you on a journey to search for hidden clues, solve puzzles, and complete challenges to ultimately uncover the ultimate prize. You'll need to put your detective skills to the test as you explore different locations and piece together the clues to progress through the game. Whether you're playing alone or with a team, get ready for a thrilling and unforgettable experience. Good luck and let the hunt begin!`,
        answer: "TEST",
        reward: "Updated",
    },
  ];
// const questions = [
// {
//     code: "QNX@2023@BLUE",
//     title: "Team Blue Question #1 - Exploring Letter Substitution and Binary Conversion",
//     description: `Use "Letter Substitution" to compute the word QUESTRONIX Then Let's take this decimal for a ride on the binary express!`,
//     answer: "10100010",
//     reward: "121",
// },
// {
//     code: "UNITY",
//     title: "Team Blue Question #2 - Caesar Cipher",
//     description: `"GEQEVEHIVMI" - Shift is in 1 - 5. That's absolute :)`,
//     answer: "CAMARADERIE",
//     reward: "150",
// },
// {
//     code: "TEAM BLUE",
//     title: "Team Blue Question #3 - Find the word",
//     description: "What elusive goal did Questronix triumphantly snatch in 1987? It's hidden within the depths of the Questronix website, waiting to be discovered by the curious and determined.",
//     answer: "THE INCEPTION",
//     reward: "106",
// },
// {
//     code: "TALI BEACH",
//     title: "Team Blue Question #4 - phlbrie kcco",
//     description: `"GUOIAITS RPNNCVI OBDGTIE" - Re-arrange the title to identify the cipher. It's not none, inline or flex`,
//     answer: "GROUP BONDING ACTIVITIES",
//     reward: "332",
// },
// {
//     code: "FINAL CODE",
//     title: "Team Blue Question #5 - Morse Code :)",
//     description: `".. - ... / -. --- - / - .... . / .- -. ... .-- . .-." - Unlocking the treasure trove isn't exactly rocket science - all it takes is a few taps of your fingers and the Final Code. It sounds simple, but beware - this digital labyrinth may have more surprises in store than you think.`,
//     answer: "FINAL CODE",
//     reward: "CONGRATULATIONS <3",
// },
// {
//     code: "QNX@2023@ORANGE",
//     title: `Team Orange Question #1 - Letter Substitution and Binary Conversion`,
//     description: `Use "Letter Substitution" to compute the word QUESTRONIX, Then Let's give this number a binary makeover and watch it go from decimal to dazzling!`,
//     answer: "10100010",
//     reward: "170",
// },
// {
//     code: "COLLABORATION",
//     title: "Team Orange Question #2 - Caesar Cipher",
//     description: `"PKCAPDANJAO" Shift is in 1 - 5. Well that's negative`,
//     answer: "TOGETHERNESS",
//     reward: "2",
// },
// {
//     code: "TEAM ORANGE",
//     title: "Team Orange Question #3 - Find the word",
//     description: "What grand achievement did Questronix unlock in 2000? It's a mystery that lies within the depths of the Questronix website - a treasure worth seeking, but not one that gives itself up easily.",
//     answer: "SYSTEM INTEGRATOR",
//     reward: "137",
// },
// {
//     code: "BATANGAS",
//     title: "Team Orange Question #4 - phlbrie kcco",
//     description: `"SRGLHVE HEOAIEN ADACEMT" - Re-arrange the title to identify the cipher. It's not none, inline or flex`,
//     answer: "SHARED GOAL ACHIEVEMENT",
//     reward: "292",
// },
// {
//     code: "LAST CODE",
//     title: "Team Orange Question #5 - Morse Code :)",
//     description: `"- .... .. ... / .. ... / -. --- - / - .... . / .- -. ... .-- . .-." - Well, it's not rocket science - just a few taps of your fingers and the Last Code will unlock the treasure trove. A cinch, really. But don't let that fool you, there's more than meets the eye to this digital labyrinth. `,
//     answer: "LAST CODE",
//     reward: "CONGRATULATIONS <3",
// },
// {
//     code: "TEST CODE",
//     title: "Default #1 - Introduction :)",
//     description: `Welcome to the Scavenger Hunt game! This exciting adventure will take you on a journey to search for hidden clues, solve puzzles, and complete challenges to ultimately uncover the ultimate prize. You'll need to put your detective skills to the test as you explore different locations and piece together the clues to progress through the game. Whether you're playing alone or with a team, get ready for a thrilling and unforgettable experience. Good luck and let the hunt begin!`,
//     answer: "TEST",
//     reward: "355",
// },
// ];

  export default questions